- hosts: all
  become: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Download email dataset
      get_url:
        url: https://www.cs.cmu.edu/~enron/enron_mail_20150507.tar.gz
        dest: /opt/enron_mail.tar.gz

    - name: unzip email dataset
      unarchive:
        src: /opt/enron_mail.tar.gz
        dest: /opt
        creates: /opt/maildir/
        remote_src: yes

    - name: create folder for processed data
      file:
        path: /opt/enron_processed
        state: directory
    
    - name: extract emails to one json
      script: utils/enron_extract_emails.py
      args:
        creates: /opt/enron_processed/enron_emails.json
    
    - name: Postgresql - create folder for data
      file:
        path: /opt/enron_processed/enron_postgresql
        state: directory

    - name: Postgresql - install python lib
      pip:
        name: "{{ packagesdep }}"
      vars:
        packagesdep:
          - python-dateutil
          - pandas

    - name: Postgresql - split data to tables
      script: utils/enron_to_postgresql.py
      args:
        creates: /opt/enron_processed/enron_postgresql/emails.csv

    - name: Postgresql - drop duplicates
      script: utils/postgresql_drop_duplicates.py
      args:
        creates: /opt/enron_processed/enron_postgresql/unique_users.csv

    - name: Postgresql - copy roles.txt
      copy:
        src: utils/roles.txt
        dest: /opt/enron_processed/enron_postgresql/roles.txt
        owner: root
        group: root
        mode: '755' 
 
    - name: Postgresql - make relationships
      script: utils/postgresql_make_relationships.py
      args:
        creates: /opt/enron_processed/enron_postgresql/unique_email_users.csv
   
    - name: Postgresql - match names with roles
      script: utils/postgresql_match_names_external.py
      args:
        creates: /opt/enron_processed/enron_postgresql/unique_users_with_names.csv
