- name: build database and import data
  vars:
    ansible_python_interpreter: /usr/bin/python3
  hosts: all
  tasks: 
  
  - name: create database directories
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - /opt/postgresql_anchor
      - /opt/postgresql_scripts
  
  - name: copy data ans secipts
    copy: src={{ item.src }} dest={{ item.dest }} remote_src={{ item.remote }}
    with_items:
      - { src: '/opt/Enron-emails-cleaning/utils/postgresql_init.sh', dest: '/opt/postgresql_anchor/01-init.sh', remote: 'no' }
      - { src: '/opt/Enron-emails-cleaning/utils/postgresql_init_nouser.sql', dest: '/opt/postgresql_scripts/02-init.sql', remote: 'no' }
      - { src: '/opt/enron_processed/enron_postgresql/emails.csv', dest: '/opt/postgresql_anchor/emails.csv', remote: 'yes' }    
      - { src: '/opt/enron_processed/enron_postgresql/unique_users_with_names.csv', dest: '/opt/postgresql_anchor/unique_users_with_names.csv', remote: 'yes' }  
      - { src: '/opt/enron_processed/enron_postgresql/unique_email_users.csv', dest: '/opt/postgresql_anchor/unique_email_users.csv', remote: 'yes' } 
  
  - name: build postgresql
    register: docker_container_output
    community.docker.docker_compose:
      project_name: databases
      definition:
        version: '3.3'
        services:
          pg_container:
            image: postgres
            restart: always
            environment:
              POSTGRES_USER: razekmh
              POSTGRES_PASSWORD: root
              POSTGRES_DB: test_db
              APP_DB_USER: docker
              APP_DB_PASS: docker
              APP_DB_NAME: docker
            ports:
              - "5432:5432"
            volumes:
              - /opt/postgresql_anchor:/docker-entrypoint-initdb.d/
              - /opt/postgresql_scripts:/opt/    
          pgadmin4_container:
            image: dpage/pgadmin4
            restart: always
            environment:
              PGADMIN_DEFAULT_EMAIL: admin@admin.com
              PGADMIN_DEFAULT_PASSWORD: root
            ports: 
              - "5050:80"
          elasticsearch:
            container_name: es-container
            image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
            environment:
              - xpack.security.enabled=false
              - "discovery.type=single-node"
            networks:
              - es-net
            ports:
              - 9200:9200
          kibana:
            container_name: kb-container
            image: docker.elastic.co/kibana/kibana:7.11.0
            environment:
              - ELASTICSEARCH_HOSTS=http://es-container:9200
            networks:
              - es-net
            depends_on: 
              - "elasticsearch"
            ports:
              - 5601:5601
          
          neo4j:
            image: neo4j:3.5
            restart: always
            ports:
              - 7474:7474
              - 7687:7687
            volumes:
              - /opt/neo4j_anchor/conf:/conf
              - /opt/neo4j_anchor/data:/data
              - /opt/neo4j_anchor/import:/import
              - /opt/neo4j_anchor/logs:/logs
              - /opt/neo4j_anchor/plugins:/plugins
            environment: 
              - NEO4J_AUTH=neo4j/somepassword
              - NEO4J_dbms_memory_pagecache_size=1G
              - NEO4J_dbms.memory.heap.initial_size=1G
              - NEO4J_dbms_memory_heap_max__size=1G   
    
        networks:
          es-net:
            driver: bridge             
 
  - name: sleep for 30 sec to wait for postgresql server
    wait_for:
      timeout: 30
    delegate_to: localhost

  - name: run the sql script
    community.docker.docker_container_exec:
      container: databases_pg_container_1
      command: bin/bash -c "psql -U docker -a -f /opt/02-init.sql"
    register: sql_script_output

