- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false

  tasks:
    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
