- hosts: all
  become: yes
  tasks:

    - name: Download email dataset
      get_url:
        url: https://www.cs.cmu.edu/~enron/enron_mail_20150507.tar.gz
        dest: /opt/enron_mail.tar.gz

    - name: unzip email dataset
      unarchive:
        src: /opt/enron_mail.tar.gz
        dest: /opt
        remote_src: yes

    - name: create folder for python scripts
      file:
        path: /opt/utils
        state: directory

    - name: create folder for processed data
      file:
        path: /opt/enron_processed
        state: directory

    - name: copy python scripts
      synchronize:
        src: /opt/Enron-emails-cleaning/utils
        dest: /opt/utils
      delegate_to: "{{ inventory_hostname }}"

    - name: extract emails to one json
      script: /opt/utils/enron_extract_emails.py

