- hosts: all
  become: no
  tasks:

    - name: Download email dataset
      get_url:
        url: https://www.cs.cmu.edu/~enron/enron_mail_20150507.tar.gz
        dest: /opt/enron_mail.tar.gz

    - name: unzip email dataset
      unarchive:
        src: /opt/enron_mail.tar.gz
        dest: /opt
        creates: /opt/maildir/
        remote_src: yes

    - name: create folder for processed data
      file:
        path: /opt/enron_processed
        state: directory
    
    - name: extract emails to one json
      script: utils/enron_extract_emails.py
      args:
        creates: /opt/enron_processed/enron_emails.json

