#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $APP_DB_USER WITH ENCRYPTED PASSWORD '$APP_DB_PASS';
	ALTER USER $APP_DB_USER WITH SUPERUSER;
	CREATE DATABASE $APP_DB_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
	CREATE USER user01 WITH ENCRYPTED PASSWORD 'simplepassword';
	GRANT CONNECT ON DATABASE $APP_DB_NAME TO user01;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$APP_DB_USER" --pasword "$APP_DB_PASS" --dbname "$APP_DB_NAME" <<-EOSQL
	GRANT USAGE ON SCHEMA public TO user01;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO user01;
	GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO user01;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO user01;
EOSQL
